
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 05 16:42:16 CST 2016
//----------------------------------------------------

package pythoncompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int L_BRACKET_OP = 39;
  public static final int CHAR_LIT = 42;
  public static final int EXCEPT = 15;
  public static final int TAB_OP = 44;
  public static final int TYPE_BOOLEAN = 32;
  public static final int COMP_OP = 33;
  public static final int INPUT = 20;
  public static final int CONTINUE = 11;
  public static final int R_PARENTHESIS_OP = 6;
  public static final int R_BRACKET_OP = 40;
  public static final int FOR = 17;
  public static final int IS_NOT = 21;
  public static final int PROPERTY_OP = 36;
  public static final int AND = 8;
  public static final int RANGE = 46;
  public static final int TYPE_LIST = 27;
  public static final int IN = 19;
  public static final int OR = 22;
  public static final int COMMA = 45;
  public static final int SEMICOLON_OP = 3;
  public static final int CLASS = 10;
  public static final int TYPE_INT = 28;
  public static final int IF = 18;
  public static final int COLON_OP = 37;
  public static final int L_PARENTHESIS_OP = 5;
  public static final int NUM_LIT = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int LOGICAL_OP = 35;
  public static final int TRY = 25;
  public static final int BREAK = 9;
  public static final int TYPE_FLOAT = 29;
  public static final int FINALLY = 16;
  public static final int ERROR = 2;
  public static final int TYPE_CHAR = 30;
  public static final int ASSIG_OP = 34;
  public static final int BOOLEAN_LIT = 41;
  public static final int ELSE = 14;
  public static final int TYPE_STRING = 31;
  public static final int RETUNR = 24;
  public static final int WHILE = 26;
  public static final int DEF = 12;
  public static final int ARITH_OP = 4;
  public static final int STRING_LIT = 43;
  public static final int ELIF = 13;
  public static final int PRINT = 23;
  public static final int IDENTIFIER = 38;
}

