
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 30 19:43:13 CST 2016
//----------------------------------------------------

package pythoncompiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int NUM_LIT = 6;
  public static final int SEMICOLON_OP = 2;
  public static final int L_PARENTHESIS_OP = 4;
  public static final int R_PARENTHESIS_OP = 5;
  public static final int EOF = 0;
  public static final int ARITH_OP = 3;
}

